
name: Upload TEST PYPY.ORG

# on:
#   push:
#     branches:
#       - 28-añadir-crear-cabecera-amsdos-para-ficheros-basic
on:
  pull_request:
    branches:
      - develop
    types:
      - closed

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build package
      run: python -m build
    - name: Publish package to TEST PYPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_SECRET }}
        repository-url: https://test.pypi.org/legacy/
        skip-existing: false
        verbose: true
# jobs:
#     release-build:
#       runs-on: ubuntu-latest
  
#       steps:
#         - uses: actions/checkout@v4
#         - uses: actions/setup-python@v4
#           with:
#             python-version: "3.x"
  
#         - name: build release distributions
#           run: |
#             python -m pip install --upgrade pip
#             python -m build
  
#         - name: upload windows dists
#           uses: actions/upload-artifact@v3
#           with:
#             name: release-dists
#             path: dist/
  
#     pypi-publish:
#       runs-on: ubuntu-latest
#       needs:
#         - release-build
#       permissions:
#         id-token: write
  
#       steps:
#         - name: Retrieve release distributions
#           uses: actions/download-artifact@v3
#           with:
#             name: release-dists
#             path: dist/
  
#         - name: Publish release distributions to PyPI
#           uses: pypa/gh-action-pypi-publish@release/v1
#           with:
#             user: __token__
#             password: ${{ secrets.TEST_PYPI_SECRET }}
#             repository-url: https://test.pypi.org/legacy/
#             skip-existing: false
#             verbose: true


# name: Upload TEST.PYPY.ORG

# on:
#   push:
#       tags:
#       - '*.*.*'

# permissions:
#   contents: read

# jobs:
#   deploy:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python
#       uses: actions/setup-python@v3
#       with:
#         python-version: '3.x'
#     - name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install build
#     - name: Build package
#       run: python -m build
#     - name: Publish package to TEST PYPI
#       uses: pypa/gh-action-pypi-publish@release/v1
#       with:
#         user: __token__
#         password: ${{ secrets.TEST_PYPI_SECRET }}
#         repository-url: https://test.pypi.org/legacy/
#         skip-existing: false
#         verbose: true
        
